config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index' #this is pointing the point to the controller, #our lookup will
  # our lookup will direct to the home#index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  #using a variable here to start the stocks api
  @api = StockQuote::Stock.new(api_key: "pk_c10395aac3814b5697d5d82713e2fe91") 
  
  # getting info from the form (coming as a parameter, and using it below), named as ticker in index.html.erb
  #error handling below
  if params[:ticker] == ""
  	@nothing = "You forgot to enter the stock symbol/code"
	  elsif params[:ticker] #if it exists
	  	begin # This beging was needed with the rescue because if 
	  		# if a wrong stock was typed, it would crash the app
	  		# the rescue avoid the app from crashing
		  	@stock = StockQuote::Stock.quote(params[:ticker])
			rescue
	  		#puts "um, that makes no sense"
	  		@error = "You typed a wrong stock symbol/code, please try again!"
		end
		
	  	#this is gonna try to render something
	  	#if !@stock #if stock doesn't exist, then go to line below
	  		#@error = "The stock symbol/code you input doesn't exist, try again"
	  	#end
	  #but we haven't sent anything to the form yet, so we need ERROR_HANDLING WITH THE IF
	  end
  end

  def about
  end

  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
	<br/>
	<div class="alert alert-warning alert-dismissable" role="alert">
		<button class="close" data-dismiss="alert">
			<small><sup>x</sup></small>
		</button>
		<%= content_tag(:div, msg) %>
	</div>


<% end %>

app/views/home/_footer.html.erb
<br/><br/><br/><br/><br/>
<center> Copyright (c) Mateus Leao </center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
        <a class="navbar-brand" href="/">
    <img src="https://cdn3.iconfinder.com/data/icons/popular-services-brands-vol-2/512/ruby-on-rails-512.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
    Stocks App
  </a>
        
        <div class="w-100 text-right">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
        <ul class="navbar-nav ml-auto flex-nowrap">
            

            <% if user_signed_in? %> 

            <li class="nav-item">  
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link m-2 menu-item" %>
            </li>


            <li class="nav-item">  
              <%= link_to "See your Stocks", stocks_path, class: "nav-link m-2 menu-item" %>
            </li>

            <li class="nav-item"> 
              <%= link_to "Add Stock", new_stock_path, class: "nav-link m-2 menu-item" %>
            </li>  


            <li class="nav-item"> 
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link m-2 menu-item" %>
            </li>
            
            <% else %>

              <li class="nav-item"> 
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link m-2 menu-item" %>
              </li>
              <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link m-2 menu-item" %>
              </li>

            <% end %>

            
            
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: "nav-link m-2 menu-item" %>
            </li>
            
        </ul>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About Me</h1>
<p> Hello!, My name is Mateus Leao and I'm learning ruby on rails! </p>

app/views/home/index.html.erb
<h1>Stocking</h1>
<%# creating a form, that points to the root_path (where it will be rendered) %>
<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
	<%= submit_tag 'Lookup' %>
<% end %>



<%# error handling just like in home controller %>
<%# the = sign after % means printing it to the screen %>
<%# this file is playing with the home_controller, sending and receiving stuff w/ parameters %>
<% if @stock %>
	<%= @stock.company_name %><br/>
	$<%= @stock.latest_price %><br/>
<% elsif @nothing %>
	<%= @nothing %>
<% end %>


<% if @error %>
		<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Stock Market App</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash' %>
      

      <br/>
   		<%= yield %>

  <%= render 'home/footer' %>

  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :stock_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= stock.user_id %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>